SWI-1687: [.NET] Unit Tests for API Models
Bandwidth/csharp-sdk pull request #71
Opened 2023-08-22 13:42 UTC by juliajanu

2023-08-25 20:38 UTC, ajrice6713 requested changes
other than the one knitpicky thing, this looks great @juliajanu!

2023-08-25 20:38 UTC, ajrice6713 commented on config.yml
can we rename this to `openapi-config.yml`? Just to be consistent + explicit

2023-08-25 20:46 UTC, juliajanu commented on config.yml
Is there a difference between the config.yml and the openapi-config.yml because that already exists...

2023-08-25 20:52 UTC, ckoegel commented on config.yml
there should only be one, I'd update `openapi-config.yml` to include the stuff you need from `config.yml` and then get rid of `config.yml`

2023-08-28 14:02 UTC, ckoegel commented on openapi-config.yml
> +TargetFramework: netstandard2.1
```suggestion
targetFramework: netstandard2.1
```

2023-08-28 15:18 UTC, ajrice6713 approved these changes

2023-08-28 15:20 UTC, merged